/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.safesail.service.persistence.Form1PK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Form1 service. Represents a row in the &quot;Safe_Sail_Form1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.safesail.model.impl.Form1ModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.safesail.model.impl.Form1Impl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Form1
 * @generated
 */
@ProviderType
public interface Form1Model extends BaseModel<Form1> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form1 model instance should use the {@link Form1} interface instead.
	 */

	/**
	 * Returns the primary key of this form1.
	 *
	 * @return the primary key of this form1
	 */
	public Form1PK getPrimaryKey();

	/**
	 * Sets the primary key of this form1.
	 *
	 * @param primaryKey the primary key of this form1
	 */
	public void setPrimaryKey(Form1PK primaryKey);

	/**
	 * Returns the uuid of this form1.
	 *
	 * @return the uuid of this form1
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this form1.
	 *
	 * @param uuid the uuid of this form1
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the sail ID of this form1.
	 *
	 * @return the sail ID of this form1
	 */
	public long getSailId();

	/**
	 * Sets the sail ID of this form1.
	 *
	 * @param sailId the sail ID of this form1
	 */
	public void setSailId(long sailId);

	/**
	 * Returns the quote ID of this form1.
	 *
	 * @return the quote ID of this form1
	 */
	@AutoEscape
	public String getQuoteId();

	/**
	 * Sets the quote ID of this form1.
	 *
	 * @param quoteId the quote ID of this form1
	 */
	public void setQuoteId(String quoteId);

	/**
	 * Returns the fullname of this form1.
	 *
	 * @return the fullname of this form1
	 */
	@AutoEscape
	public String getFullname();

	/**
	 * Sets the fullname of this form1.
	 *
	 * @param fullname the fullname of this form1
	 */
	public void setFullname(String fullname);

	/**
	 * Returns the dob of this form1.
	 *
	 * @return the dob of this form1
	 */
	public Date getDob();

	/**
	 * Sets the dob of this form1.
	 *
	 * @param dob the dob of this form1
	 */
	public void setDob(Date dob);

	/**
	 * Returns the gender of this form1.
	 *
	 * @return the gender of this form1
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this form1.
	 *
	 * @param gender the gender of this form1
	 */
	public void setGender(String gender);

	/**
	 * Returns the phone no of this form1.
	 *
	 * @return the phone no of this form1
	 */
	public long getPhoneNo();

	/**
	 * Sets the phone no of this form1.
	 *
	 * @param phoneNo the phone no of this form1
	 */
	public void setPhoneNo(long phoneNo);

	/**
	 * Returns the email address of this form1.
	 *
	 * @return the email address of this form1
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this form1.
	 *
	 * @param emailAddress the email address of this form1
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the pan number of this form1.
	 *
	 * @return the pan number of this form1
	 */
	@AutoEscape
	public String getPanNumber();

	/**
	 * Sets the pan number of this form1.
	 *
	 * @param panNumber the pan number of this form1
	 */
	public void setPanNumber(String panNumber);

	/**
	 * Returns the annual income of this form1.
	 *
	 * @return the annual income of this form1
	 */
	public long getAnnualIncome();

	/**
	 * Sets the annual income of this form1.
	 *
	 * @param annualIncome the annual income of this form1
	 */
	public void setAnnualIncome(long annualIncome);

	/**
	 * Returns the sum assured of this form1.
	 *
	 * @return the sum assured of this form1
	 */
	public long getSumAssured();

	/**
	 * Sets the sum assured of this form1.
	 *
	 * @param sumAssured the sum assured of this form1
	 */
	public void setSumAssured(long sumAssured);

	/**
	 * Returns the policy term of this form1.
	 *
	 * @return the policy term of this form1
	 */
	public int getPolicyTerm();

	/**
	 * Sets the policy term of this form1.
	 *
	 * @param policyTerm the policy term of this form1
	 */
	public void setPolicyTerm(int policyTerm);

	/**
	 * Returns the pp term of this form1.
	 *
	 * @return the pp term of this form1
	 */
	public int getPPTerm();

	/**
	 * Sets the pp term of this form1.
	 *
	 * @param PPTerm the pp term of this form1
	 */
	public void setPPTerm(int PPTerm);

	/**
	 * Returns the payment frequency of this form1.
	 *
	 * @return the payment frequency of this form1
	 */
	@AutoEscape
	public String getPaymentFrequency();

	/**
	 * Sets the payment frequency of this form1.
	 *
	 * @param paymentFrequency the payment frequency of this form1
	 */
	public void setPaymentFrequency(String paymentFrequency);

	/**
	 * Returns the payout option of this form1.
	 *
	 * @return the payout option of this form1
	 */
	@AutoEscape
	public String getPayoutOption();

	/**
	 * Sets the payout option of this form1.
	 *
	 * @param PayoutOption the payout option of this form1
	 */
	public void setPayoutOption(String PayoutOption);

	/**
	 * Returns the life secure of this form1.
	 *
	 * @return the life secure of this form1
	 */
	public int getLifeSecure();

	/**
	 * Sets the life secure of this form1.
	 *
	 * @param lifeSecure the life secure of this form1
	 */
	public void setLifeSecure(int lifeSecure);

	/**
	 * Returns the life plus of this form1.
	 *
	 * @return the life plus of this form1
	 */
	public int getLifePlus();

	/**
	 * Sets the life plus of this form1.
	 *
	 * @param lifePlus the life plus of this form1
	 */
	public void setLifePlus(int lifePlus);

	/**
	 * Returns the cip benefit of this form1.
	 *
	 * @return the cip benefit of this form1
	 */
	public int getCIPBenefit();

	/**
	 * Sets the cip benefit of this form1.
	 *
	 * @param CIPBenefit the cip benefit of this form1
	 */
	public void setCIPBenefit(int CIPBenefit);

	/**
	 * Returns the total values of this form1.
	 *
	 * @return the total values of this form1
	 */
	public long getTotalValues();

	/**
	 * Sets the total values of this form1.
	 *
	 * @param totalValues the total values of this form1
	 */
	public void setTotalValues(long totalValues);

	/**
	 * Returns the total addon of this form1.
	 *
	 * @return the total addon of this form1
	 */
	public long getTotalAddon();

	/**
	 * Sets the total addon of this form1.
	 *
	 * @param totalAddon the total addon of this form1
	 */
	public void setTotalAddon(long totalAddon);

	/**
	 * Returns the agreement of this form1.
	 *
	 * @return the agreement of this form1
	 */
	public Boolean getAgreement();

	/**
	 * Sets the agreement of this form1.
	 *
	 * @param agreement the agreement of this form1
	 */
	public void setAgreement(Boolean agreement);

	@Override
	public Form1 cloneWithOriginalValues();

}